---
shardCount: 1
prefix:
  - "/"
status: online
game:
  type: Playing
  name:
    - "with NUMBERS"
  url: https://tinyurl.com/stemdiscord
  interval: 60
music:
  status: true
  passes: 1
logLevel: 6
